CREATE SEQUENCE SEQ_USER_ID INCREMENT BY 1 START WITH 1 ORDER;

CREATE TABLE USER_DETAILS
(
   id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
   name varchar(100) NOT NULL,
   email varchar(100) NOT NULL,
   mobile_number varchar(100) NOT NULL
);